add_newline = false
format = """${custom.fish_private}${all}"""

[character]
success_symbol = "[Ï„](bold green)"
error_symbol = "[Ï„](bold red)"

[status]
disabled = false

[shlvl]
disabled = false
symbol = "â†•ï¸ "
threshold = 3

[git_status]
deleted = "âœ"
format = '([$all_status$ahead_behind]($style) )'

# https://github.com/starship/starship/issues/2144
[custom.fish_private]
when = 'test -n "$FISH_PRIVATE_MODE"'
description = "Indicates that fish shell is in private mode"
symbol = "ğŸ™ˆ "
style = "purple"
shell = 'sh'

